baseURL = ''
title = 'Hugo Monteiro'
languageCode = 'en-uk'
defaultContentLanguage = "en-uk"
enableEmoji = true

# Automatically generate robots.txt
enableRobotsTXT = true

# Basic Configuration: https://gokarna-hugo.netlify.app/posts/theme-documentation-basics/
# Advanced Configuration: https://gokarna-hugo.netlify.app/posts/theme-documentation-advanced/
theme = 'gokarna'

# Hugo lets you choose the color scheme for the codeblocks. 
# You can choose from the options here: https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "monokai"

# Favicons, Browserconfig, Manifest
# It is recommended to put your own favicons:
# 
# apple-touch-icon.png (180x180)
# favicon-32x32.png (32x32)
# favicon-16x16.png (16x16)
# mstile-150x150.png (150x150)
# android-chrome-192x192.png (192x192)
# android-chrome-512x512.png (512x512)
# into /static directory. They’re easily created via favicon.io or realfavicongenerator.net.
# 

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  AvatarAltText = "Hugo Monteiro"

  # Description to display on homepage
  description = "Solution Designer / Architect for SCM Applications"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
# You can use this to inject any HTML in the <footer> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customFooterHTML ="Some men see things as they are and say, 'Why?'<br> I dream things that never were and say, 'Why not?'"

  # Keywords relevant for SEO
  metaKeywords = ["blog", "hugo monteiro", "software", "developer", "javascript", "ci/cd", "solution designer", "architect", "scm", "technical notes"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "Hugo Monteiro"
  footerdescription = ""

  # The date format being used across can be chaged. 
  # For valid date strings see: https://pkg.go.dev/time#pkg-constants
  dateFormat = "2 January, 2006"

  # At the bottom of a post, show the previous and next post chronologically.
  # Warning: Not compatible with the .Weight parameter.
  # If any post YAML contains weight:, the posts will not appear by Date. See Hugo’s default sort.
  togglePreviousAndNextButtons = "true"

  socialIcons = [
      {name = "github", url = "https://github.com/hvmonteiro"},
     {name = "twitter", url = "https://example.com/hvmonteiro"},
     {name = "linkedin", url = "https://example.com/hvmonteiro"},
#     {name = "bluesky", url = "https://hvmonteiro.bsky.social"},
     {name = "buymeacoffee", url = "https://www.buymeacoffee.com/hvmonteiro"}
  ]



[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false


[menu]

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "home"
    # Display name
    name = "Home"
    url = "/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='home'></span>"
    # We use feather-icons: https://feathericons.com/
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # Weights are used to determine the ordering
    weight = 10

  [[menu.main]]
    identifier = "about"
    url = "/about/"
    name = "About"
    pre = "<span data-feather='user'></span>"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    weight = 30

  [[menu.main]]
    identifier = "technical-notes"
    name = "Technical Notes"
    url = "/technical-notes/"
    pre = "<span data-feather='terminal'></span>"
    weight = 40

  [[menu.main]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    pre = "<span data-feather='hexagon'></span>"
    weight = 50

  [[menu.main]]
    identifier = "desksetup"
    name = "Desk Setup"
    url = "/desksetup/"
    pre = "<span data-feather='monitor'></span>"
    weight = 60

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 70

  #[[menu.main]]
    #identifier = "github"
    #url = "https://github.com/hvmonteiro"
    #pre = "<span data-feather='github'></span>"
    #weight = 80

  #[[menu.main]]
    #identifier = "linkedin"
    #url = "https://linkedin.com/hvmonteiro"
    #pre = "<span data-feather='linkedin'></span>"
    #weight = 90

  #[[menu.main]]
    #identifier = "buymeacoffee"
    #url = "https://www.buymeacoffee.com/hvmonteiro"
    #pre = "<span data-feather='coffee'></span>"
    #weight = 100

  [[menu.main]]
    identifier = "Orcid"
    url = "https://orcid.org/0009-0006-7405-6746"
    pre = "<span data-feather='divide-square'></span>"
    weight = 110

  [[menu.main]]
    identifier = "RSS"
    url = "/index.xml"
    pre = "<span data-feather='rss'></span>"
    weight = 120

